### ISSUE TITLE
Make attacks with light weapons automatically eased by 1 step

### ISSUE THREAD

**Issue by gonzaPaEst** [mrkwnzl/cyphersystem-foundryvtt#148]
**Is your feature request related to a problem? Please describe.**  
Not sure if this applies to all Cypher settings, but in Numenéra and the CSR, it states that attacks with light weapons are eased (Discovery p. 95 and CSR Revised p. 203).

**Describe the solution you'd like**  
Add the following code (or similar) to the pc-sheet.js file:

```
let attackModifier = 0;
if (i.data.attackType == "light weapon") attackModifier = 1;
totalModifier = skillRating + modifiedBy + attackModifier;
```

Final result:

  ```
getData() {
    const data = super.getData();
    const actorData = data.actor.data;

    for (let i of data.items) {
      if (i.type == 'attack' || i.type == 'teen Attack') {

        let skillRating = 0;
        let modifiedBy = i.data.modifiedBy;
        let totalModifier = 0;
        let totalModified = "";
        let attackModifier = 0;

        if (i.data.skillRating == "Inability") skillRating = -1;
        if (i.data.skillRating == "Trained") skillRating = 1;
        if (i.data.skillRating == "Specialized") skillRating = 2;

       if (i.data.attackType == "light weapon") attackModifier = 1;

        if (i.data.modified == "hindered") modifiedBy = modifiedBy * -1;

       totalModifier = skillRating + modifiedBy + attackModifier;

        if (totalModifier == 1) totalModified = game.i18n.localize("CYPHERSYSTEM.eased");
        if (totalModifier >= 2) totalModified = game.i18n.format("CYPHERSYSTEM.EasedBySteps", {amount: totalModifier});
        if (totalModifier == -1) totalModified = game.i18n.localize("CYPHERSYSTEM.hindered");
        if (totalModifier <= -2) totalModified = game.i18n.format("CYPHERSYSTEM.HinderedBySteps", {amount: Math.abs(totalModifier)});

        // Assign and return
        i.data.totalModified = totalModified;
        this.actor.updateEmbeddedDocuments("Item", [i]);
      }
    }
```

**Describe alternatives you've considered**  
I could just add a +1 in the Modifier, but since you are automatically applying "eased by" with Trained and Specialized, I thought it would be nice to do the same with Light Weapons.

**Setup**  
Cypher System Version: 1.15.5
Foundry VTT Version: 7.10  
Native App/Browser: Chrome  

**Additional context**  
As you can see, I am using an older version of both Foundry and the Cypher System, so I actually implemented the code on my own game already. I just thought you would like to consider it for the actual (current) system. Thanks!

**Comment by mrkwnzl** [comment]
To be honest, I don’t think that would be a good idea. It would be a breaking change for all existing light weapons, for all characters and in all compendia. This was different for the skills because it defaults to practiced, so if users didn’t change that setting by hand, everything worked as before.

It might also confuse some people, as that modifier wouldn’t come up anywhere but the results. When people are using the All-in-One macro, they don’t have the ability to enter that they are using a light weapon, so they need to fill out the “eased by” input, unless they are using the item macro with the setting to use the All-in-Pne dialog, in which case the attack is modified even if it doesn’t show up in the dialog. I’d like to keep that consistent and the All-in-One dialog simple, and that dialog borders on the upper limit of complexity already.

That’s one of these cases of automation I’d like to avoid because it’s not under the control of the players.

**Comment by mrkwnzl** [comment]
One thing, that I haven’t mentioned, though. Even if I think that this wouldn’t be something for the core system, I’d love to see stuff like this as small modules for people who’d like that. @NiceTSY is working on his module and custom character sheet, so maybe that’s something that could be included there. I’m more than happy to help with the code and I’ll try to give access to all functions of the system via an API so that they can be easily extended or overwritten by modules.

**Comment by NiceTSY** [comment]
That could be a good idea to add to my module indeed. Let me see how I can handle that :D 
If you do more API functions that could be awesome too! Cannot wait to play with them.

**Comment by mrkwnzl** [comment]
> That could be a good idea to add to my module indeed. Let me see how I can handle that :D
> If you do more API functions that could be awesome too! Cannot wait to play with them.

Let me know what you need access to. I don’t really want to randomly put some parts in there without a concept. I don’t think that would be good for the code.

**Comment by mrkwnzl** [comment]
Closing this for now, as @NiceTSY might implement that in his module. If a new idea comes along for this, ideally non-breaking for existing worlds, feel free to re-open this.
