### ISSUE TITLE
Change Roll Dice Card

### ISSUE THREAD

**Issue by farling42** [mrkwnzl/cyphersystem-foundryvtt#238]
**Is your feature request related to a problem? 
No

**Describe the solution you'd like**  
It would be nice if the Dice Card in the chat window didn't shows the 1d20 line, since it is redundant and just makes the card bigger.
Also, it would be nice to see the beaten difficulty in the bottom box of the roll dice card - either as an alternative to the dice roll result, or as an additional part of the displayed string.
```
17 (beats difficulty 5)
```

**Comment by mrkwnzl** [comment]
Still not sure about that one. I actually like it the way it is. Sometimes, the actual die roll is important. With the chat output being easily overwritten in v2.0.0, and some re-stylings of the default, this might become less of an issue. Let’s revisit this after v2.0.0 releases.

**Comment by farling42** [comment]
I'm happy to wait.
The actual dice roll can be seen by clicking on the bottom button that is present in each chat bar - so hiding it unless it is really required.

**Comment by mrkwnzl** [comment]
There has been some re-styling of the chat output to make the beaten difficulty more prominent as well as a note whether the roll was successful if a difficulty has been set.

The chat output also has a new function that can be more easily overwritten, getting a roll object which includes all the info and most of the computation, so that the chat output only needs to be styled. The different elements of the chat output also got css classes so that they can be re-styled using css modules.

I consider this to be closed for now. Feel free to re-open in case of further discussion needed.
