### ISSUE TITLE
Bigger "GM Intrusion!" in Chat card

### ISSUE THREAD

**Issue by farling42** [mrkwnzl/cyphersystem-foundryvtt#239]
I feel that a bigger font for the "GM Intrusion!" text in the chat card would highlight it much better to excite both the players and the GM :-)

Similarly for the 19-20 die results.

**Comment by mrkwnzl** [comment]
We’ve had the idea in the past that there might a module to style the chat cards differently. That’s why I put the chat card contents into functions as part of the cyphersystem object. They can easily overwritten this way. Maybe we should follow through with that idea. Part of that was to have different stylings for different genres, for example.

**Comment by farling42** [comment]
Ah, I could have a look at how easy a module can change the styling then :)

**Comment by farling42** [comment]
Can the possibleEffects variable in roll-engine-dice-roller be changed to use a style named in the CSS file for each effect instead of static fixed colours?
Maybe each style can be named after the effect (as per the name of the localize variable)

**Comment by mrkwnzl** [comment]
There are two things in v2.0.0 that could accommodate that: 

(1) All the roll info is now stored in an object and passed into the output function. All calculations are done beforehand, so the output function could be replaces with a custom one with relative ease.

(2) The roll results and effects now have custom css classes that can be overwritten, so that the existing output can be easier styled as well.

I played around with the styling, and I’m honestly pretty satisfied with the way it looks now, so I’ll let any restyling up to module creators.

**Comment by mrkwnzl** [comment]
Well, I did a little bit of styling. The roll results and effects are bold now.
