### ISSUE TITLE
Object Damage Track

### ISSUE THREAD

**Issue by homiedion** [mrkwnzl/cyphersystem-foundryvtt#284]
Requesting an “object damage track” field be added to items. Potentially including a blurb about the effects of the various damage levels similar to the damage track found in player sheets or any option to print said blurb out when an item is displayed to chat.

**Comment by mrkwnzl** [comment]
Hey! Could you elaborate in what situations that would be useful? Given that damage either reduces the level of an object (which I believe wouldn't do much, would it?) or is no longer functioning. I'm not sure in which situations tracking that would be useful.

**Comment by homiedion** [comment]
For reference the general steps of the ODT are:
* Intact
* Minor Damage (functions as 1 level lower)
* Major Damage (no longer functions)
* Destroyed (cannot be repaired)

Campaigns wanting to put an emphasis on resource scarcity may to use a keep track of if an item is recoverable.


I’ve personally mixed the ODT with the vehicle rules to track how damaged space ship parts were and if they were still repairable though it was tracked through the description. Would been a godsend to have a field I could access via macros.

**Comment by mrkwnzl** [comment]
All right, handling ship systems and their damage in vehicle actors is something different than a general damage track for objects.

I can say that I won't put house rules into the system, so there won't be a damage track for ship systems, as those are handled differently, when I understood the rules correctly. That doesn't mean we can't improve upon vehicle actors and starship systems, though.

But can you be more specific about what exactly you imagine? Right now, it sounds like you want to be able to track the damage of the sword of a character, for example. Is that what you have in mind primarily or is this about improving on starships?

Sorry if that sounds a bit nitpicky, but I need to know specifics about your use case and why you want that in the system in order to see if I can provide that. For example, I can't really just put a damage track into all items, as that doesn't make sense for most of the item types. And conceptually, it doesn't really make sense for attacks either, as those don't necessarily correlate with single objects. There could be multiple attacks for a single sword, for example. So are you asking about a damage track for equipment items? Just as an illustration what kind of decisions I need to make, so being as specific as possible would be helpful to me.

**Comment by homiedion** [comment]
Oh nothing to fret about I understand. I’ll give a better answer when I get back to my desktop

**Comment by mrkwnzl** [comment]
Thanks! Looking forward to it!

**Comment by homiedion** [comment]
Went on a bit of a tangent in the last one so gonna back up and clarify.

My general thought is to add a small drop down menu; similar to the damage track on PC sheets, to item sheets. Equipment, cyphers and artifacts would likely be the primary target of this addition as the former is more likely to see regular use (and thus possibly be subject to GMIs that move it down the object damage track, break it, etc.) and the latter two often have effects that are impacted by their level.

While this can be achieved by storing its state in any item's plain text description, having a field potentially allows this data to be more easily accessed and displayed. Potential uses that come to mind are:

- Displaying the object damage track of items in an inventory in a similar manner to displaying quantities or level
- Allowing macros to modify the state of the ODT on an object
- Allowing items displayed to chat to print out relevant rules (ie. minor damage: level reduction, major damage: broken but repairable, Destroyed: Cannot be repaired)

**Comment by mrkwnzl** [comment]
Sorry, I’m not trying to be dense. I see how the damage track could be used on the sheet and in macros, but I’m not quite sure what problem this would solve *in your game*. Does damaged equipment play such a big role Cypher games that this occurs regularly? Here’s my understanding, but you might have a different perspective:

**Equipment**, at least in the SRD, doesn’t generally have or use its level in a whole lot of situations, so minor damage does basically nothing. I’d think that in most games, GM intrusions are used to make the item non-functional or to destroy it outright, so tracking its level or damage isn’t really necessary in actual play. I’d imagine that archiving items (when not functional) or simply deleting it (when it’s destroyed) is easier and preferred by most.

**Cyphers** might suffer from minor damage as they have and regularly use their level, but as one-time use items I’d expect that GM’s aren’t often targeting them in such a way. I’d expect that in cases where they are damaged, they aren’t long enough in the game to really be repaired, so in most cases it’s sufficient to just reduce their level. Major damage and destruction can also more easily achieved by archiving and deleting, respectively.

I guess I see the benefit of a damage track for **artifacts** the most, as they are used for a long time and they would be worth repairing. But I’m not sure if the effort to add that to the system just for artifacts is worth it.

Please don’t get me wrong, I don’t want to dismiss your ideas, but I also try to keep the system from bloating. To do that, I try to understand how certain features would be used in actual games and whether there are other ways of achieving that. So I always ask about how a new features would solve problems in the game, and I guess I don’t yet see how the damage track would be used with regularity on the player’s side. I always saw that rather as a GM’s tool to deal with non-NPC challenges. For example, I recently used the damage track for a wall the PCs were trying to break through before the goblin horde caught up on them. In these cases that minor damage makes more sense as well, as minor damage makes it easier to inflict major damage or outright destroy the item. But I haven’t really seen minor damage as a way to make the item less effective (because in most cases, the level really doesn’t matter).

**Comment by homiedion** [comment]
Perfectly fair to not want things to bloat, figured I’d at least propose the idea. Closing this.
