### ISSUE TITLE
When adding or updating an Item set archived state based on tags

### ISSUE THREAD

**Issue by farling42** [mrkwnzl/cyphersystem-foundryvtt#306]
When using tags or recursions, it would be nice if the archived state was set correctly when an Item is first created or subsequently edited.

(I know that I can manually select the tag/recursion again to set the correct state, but it would be a QOL improvement to have it happen automatically.)

**Comment by mrkwnzl** [comment]
I think that’s really hard to implement, at least with the current way how Recursions work. Thing is, I can’t tell Foundry to not change the archive status if something else that is not the recursion tag has been changed. And in the next update, there will be a way to drag foci, which is a way to keep items active even if you aren’t on the tagged recursion.

For example, I have a certain focus on Earth and it can be dragged to Ardeyn. When I drag that focus, my abilities, skills, and equipment stay the same on Ardeyn. If I now implement a automatism that archives or unarchives the items based on the current recursion when I update the items, for example because I reduced the quantity, or fixed a typo, they are being archived although I don’t want that. How can I tell Foundry when to do it when not to do it?

I like the idea, and I’ll keep thinking about a way to implement that, but right now, I’d rather stay on the side of keeping it in the player’s hand to archive or unarchive the appropriate items, either be doing it on the item or by translating to another (or even the same) recursion. And if you have an idea on how to tackle that within the current recursion functionality, please let me know.

**Comment by farling42** [comment]
Ah, I guess my "editing" idea was about adding a recursion to an Item that didn't currently have one.

Being able to do it on initially adding an Item to an Actor would be a nice QOL improvement though.

At some point I might have a look at the code to see what is easily possible :)

**Comment by mrkwnzl** [comment]
This is implemented in the tagging overhaul in v2.12.0
