### ISSUE TITLE
Setting to change scene default measurements

### ISSUE THREAD

**Issue by pwykersotz** [mrkwnzl/cyphersystem-foundryvtt#361]
It would be a nice quality of life feature to add a settings option to change the default scene creation Grid Scale Distance/Units to something other than 1.5 meters. 5ft being my typical use case, though being able to fill in custom defaults would be super neat. Thanks for considering!

**Comment by mrkwnzl** [comment]
Thank you for your suggestion.

The currently intended and way more powerful way would be to create a template scene with all the settings you like, and duplicating that instead of creating new ones. That is more flexible, can be shared across worlds (by importing or by creating a compendium module), and is more powerful because you can set *all* your own defaults.

Would that work for your use case?

**Comment by mrkwnzl** [comment]
I hear you, but my point stands: It’s one template, then, with all the defaults that *all* scenes share, and duplicate that instead of creating a new one.

The reason why I’m reluctant to implement this is twofold: (1) Knowing the user base, once there’s a setting for the grid distance, there will be demand for default settings for the grid type, and probably other settings as well. At this point, I’m simply duplicating what’s already there: that you can prepare a scene which is the basis for new scenes, with the only difference that one is a template scene and the other is a window in the settings. (2) It’s hard to communicate that you can set *one* default value in the settings, but you need a template scene for setting other default values. I’d rather explain that you can always create a template scene/actor/item/table and duplicate that. That is universal, flexible, and powerful (since you can change *all* the values, then).

I hope that makes sense to you.

As a third option, and I’m not sure how useful that would be for your use case, you could use a simple macro to create a new scene. Like this one:

```js
Scene.create({
  "name": "Imperial Scene",
  "grid.distance": 5,
  "grid.units": "ft"
});
```

With a single click, you now create a scene named “Imperial Scene” (that can be changed, of course) with a grid distance of 5 ft instead of 1.5 m. This can be expanded as well, for all other values a scene might have. I’m happy to help out with that. Would that be a viable alternative?

**Comment by mrkwnzl** [comment]
Closing this for spring cleaning. Feel free to open this again if there’s something to add.
