### ISSUE TITLE
[Feature Request] Click-to-increment function for Pools

### ISSUE THREAD

**Issue by MithralDream** [mrkwnzl/cyphersystem-foundryvtt#40]
Two small buttons that appear when hovering over a fill-in field for Pools to increase or decrease it by 1 would be much faster for small adjustments than having to erase the number and filling in the new number.
![image](https://user-images.githubusercontent.com/77936659/105641450-5930da80-5e84-11eb-9edb-fb9c2e72a501.png)
Example from the Roll20 Numenera sheet

**Comment by mrkwnzl** [comment]
Those arrows make more problems than they solve, as they can be activated with the mouse wheel. High definition mouse wheels and trackpads tend to activate them accidentally. Various browsers also have difficulty with those, especially if they are getting scaled down, which would be needed for the character sheet, which usually makes the down button unreachable. Several game systems have those removed for the exact same reason. Sorry.

Double clicking the field selects the whole text so that you can simply enter the new value, without erasing it first.

**Comment by mrkwnzl** [comment]
I re-opened this because I’ve had an idea last night. I won’t put these specific arrow buttons on there, for the mentioned reasons. But I’ll see if I can find a different solution, similar to the buttons for quantity.

**Comment by mrkwnzl** [comment]
Work in progress:

<img width="203" alt="Bildschirmfoto 2021-01-29 um 11 40 20" src="https://user-images.githubusercontent.com/40534855/106265087-d1055900-6226-11eb-9470-9955131aca8e.png">

I’m not sure I like how that looks. What do you think?

**Comment by mrkwnzl** [comment]
I think I found a way with which I’m satisfied:

<img width="613" alt="Bildschirmfoto 2021-01-29 um 21 11 50" src="https://user-images.githubusercontent.com/40534855/106322811-ae9b2c00-6276-11eb-95ba-513b6468c88e.png">

I moved the reset button into the label, so that you can click “Might“ to reset Might. Thoughts?

**Comment by MithralDream** [comment]
> I moved the reset button into the label, so that you can click “Might“ to reset Might.
Sounds like a good workaround. Maybe move the arrow buttons a bit further away from the pool names, since one wrong click would mean a reset.
An instant tooltip when hovering over the pool name like "Fill pool to max" could also save a little bit of confusion for new players since clickable Attribute names usually roll it.

**Comment by mrkwnzl** [comment]
I’ll have a tooltip there, but I can’t make it instant. That is handled by the browser. I’m not too worried about accidental mis-clicks, as you’d have to misalign your click by a lot. The hit box is pretty accurate. But I’ll adjust it if it does happen.

Thanks!
