### ISSUE TITLE
[Feature Request] Default Pool on Skills

### ISSUE THREAD

**Issue by CaelReader** [mrkwnzl/cyphersystem-foundryvtt#61]
I like to setup preset Speed/Might/Intellect Defense entries on player sheets so they can easily just add them to their macro bar without having to make the skills themselves. However, now players keep accidentally spending Might points when they apply effort, since that's what the macro defaults to, and they have to go in and change the pool on each of their macros individually. It would be handy if a skill could also be assigned to a Pool in the skills dialogue, same way it gets assigned a training level, that way it would automatically use the right pool when turned into a macro.

**Comment by mrkwnzl** [comment]
What macro are you using to spend Effort? The Spend Effort macro?

Thing is, even if a pool is set, that wouldn’t help as the skill macros don’t let you spend Effort. The system doesn’t know whether you want to spend Effort and how much. The item macros you generate are quick roll macros where you don’t spend any pool points.

I have, however, prepared two other macros you could use.

(1) The Quick Roll (All-in-One Template) lets you assign a pool and a point cost, so it will always automatically just spend those points. But then you can’t change how many levels of Effort you want to spend. It’s a quick roll macro and just works with one click, always the same.

(2) The All-in-One Roll macro. That opens up a dialog where you can specify the Levels of Effort and other factors. When you edit the macro, you can set different defaults. So you could set multiple of this macro up and set them to the skill level and correct pool and use that instead instead of the quick roll macros you get by dragging the item to the bar.

**Comment by CaelReader** [comment]
Er, when I drag a Skill into the Macro Bar, it results in an All-in-One Roll macro, just with the Skill Level pre-selected. I can totally spend effort and all that using said macro. Is that not supposed to be what's happening? 

Yea, you can edit the macro directly, but it'd just be convenient if I could set up, ie, Speed Defense as a skill and have it set to the Speed pool, so that when a player drags it to their macro bar it just automatically uses Speed by default, instead of the player having to edit the macro into using Speed themselves.

**Comment by mrkwnzl** [comment]
Since you haven’t mentioned anything different, I was assuming that you were using the default settings, where the macro is just a quick roll macro.

If you set the setting to use the dialog instead, the way is to modify the macro, not the skill. I’m building the system for the default settings, and a pool setting for skills would do nothing. It would just confuse people as to why they should set it.
