### ISSUE TITLE
[Feature Request] Different categories for abilities

### ISSUE THREAD

**Issue by Roffelchen** [mrkwnzl/cyphersystem-foundryvtt#66]
**Is your feature request related to a problem? Please describe.**  
The abilities tab in the character sheets auto-sorts alphabetically. This is actually quite nice, but it leads to missing oversight over which abilities are actions and enablers.

**Describe the solution you'd like**  
A (potentially optional) subcategory for abilities, to divide them into actions and enablers. Like the subcategories of the equipment tab.

**Describe alternatives you've considered**  
So far I named actions "A Name" and enablers "E Name". Which is at least a temporary fix.

**Setup**  
Cypher System Version: 1.13.4 
Foundry VTT Version: 0.7.9  
Native App/Browser: Desktop App (so Chromium)

**Additional context**  
No more context. But thank you for you work :)
While I was initially put off by the "non-functional" character sheets, I grew to love them!
Nice work with the all in one Macros!

**Comment by mrkwnzl** [comment]
Thanks for the suggestion. I thought about this, but there’s one problem. There are multiple sensible ways to sort abilities: 

- By actions and enablers
- By active and passive (things like armor training being active, but actions and enablers as part of another action being active) 
- By source (Type, Descriptor, Focus)
- By theme (magic, mundane)
- By function (social, combat)
- By point cost
- By stat pool
- By tier

The best way to accommodate that, that I can think of, is by simply sorting it alphabetically, and do exactly what you do. I even have a heading in the wiki for that, but I didn’t get around writing it down: [https://github.com/mrkwnzl/cyphersystem-foundryvtt/wiki/Tips-&-Tricks#sorting--categorizing-skills-abilities-and-equipment](https://github.com/mrkwnzl/cyphersystem-foundryvtt/wiki/Tips-&-Tricks#sorting--categorizing-skills-abilities-and-equipment)

Personally, I’d put that in brackets before the name: [Action] Onslaught or [Enabler] Adroit Cypher Use, so that I can easily recognize that it’s a sorting determinate.

**Comment by mrkwnzl** [comment]
Closing this issue for now. @Roffelchen, feel free to re-open if you have a good idea for sorting abilities.
