### ISSUE TITLE
[Feature Request] Add Pool to Skills/Training to Abilities

### ISSUE THREAD

**Issue by cityofkeats** [mrkwnzl/cyphersystem-foundryvtt#68]
**Is your feature request related to a problem? Please describe.**  
Skills can be dragged to the macro bar, but they will not have a pool associated with them, requiring manual configuration of the AiO macro defaults if something like effort is desired.

Abilities can be dragged to the macro bar, but have no training level, requiring manual configuration of the AiO macro defaults to automatically keep track of the difficulty modifier associated with being trained/specialized/etc.

**Describe the solution you'd like**  
Add a dropdown to skills to assign them a particular pool, and reflect this in the associated All-in-One Macro defaults.

Add a dropdown to abilities to assign them a training level, and reflect this in the associated All-in-One Macro defaults.

**Describe alternatives you've considered**  
The only clear alternative at the moment is as written above: manually change the macro defaults for the All-in-One Roll

**Setup**  
Cypher System Version: 1.13.7
Foundry VTT Version: 0.7.9
Native App/Browser: Chrome

**Additional context/side note**  
This applies primarily to using macros with the All-in-One Roll system. Regular quick roll macros do not appear to be editable in a way that functions properly, which may be a bug (e.g. changing the pool on a quick roll macro doesn't actually impact which pool is drawn from). Is this expected behavior?

**Comment by mrkwnzl** [comment]
Thanks for the suggestion!

> The only clear alternative at the moment is as written above: manually change the macro defaults for the All-in-One Roll

That is indeed the intended way. Here’s my thought process on this: I assume that by default, people play the game as written. That is, before any roll, a discussion about the difficulty and how that difficulty is modified. The players then pay all the cost (either directly on the sheet, on the token, if they have Bar Brawl installed, or by using the Spend Effort macro) and then roll an unmodified roll against the modified difficulty (using the Quick Roll macro). By default, skills aren’t tied to a particular pool, and abilities don’t have skill levels. Question is, what should the dropdowns do when you play the default way? If they don’t do anything, they shouldn’t be on the character sheet.

There is a hard demand for a dialog where people can input all the info from the discussion before a roll so that everything then is calculated and they don’t have to subtract points themselves. While I don’t personally play that way, I want to accommodate that play style. That’s why there is the All-in-One Roll macro and the option for dragged abilities to use the same dialog. My thinking is that if you want to use the macros, and want the macros to default to different values, edit the macro. I auto-populate the macros with values from the character sheet, if the values are already there, but I only put any values on the character sheet if it makes sense even without the macro. For everything else, I tried to make editing the macro as easy as possible.

I don’t see how a stat pool on skills and a skill level on abilities is useful if you don’t use the All-in-One dialog. I’m open to ideas for that, but I won’t put it in there only for the macros.

> Regular quick roll macros do not appear to be editable in a way that functions properly, which may be a bug (e.g. changing the pool on a quick roll macro doesn't actually impact which pool is drawn from). Is this expected behavior?

What quick roll macro were you trying to edit, exactly? There’s the Quick Roll macro, the Quick Roll (All-in-One Template), and item macros when you don’t have the system setting *Item Macros Use All-in-One Dialog* enabled. All of these are quick roll macros, which generally don’t do anything apart from rolling. Item macros from abilities subtract their point cost, in addition to the roll.

The defaults for item macros are for the dialog only. They don’t have any impact on anything when the system setting *Item Macros Use All-in-One Dialog* is disabled.

Could you elaborate on that?

**Comment by mrkwnzl** [comment]
I’ll close this issue for now. If you have any more ideas on that, feel free to re-open.

**Comment by mrkwnzl** [comment]
@cityofkeats Just wanted to let you know that I finally gave in an implemented roll buttons on the character sheet, which does exactly what you wanted here, I believe. The values still need to be adjusted manually, though, so it’s not really a reduction of work, but you don’t have to edit macros anymore, but have a GUI for that.
