### ISSUE TITLE
Translation of system settings

### ISSUE THREAD

**Issue by mrkwnzl** [mrkwnzl/cyphersystem-foundryvtt#73]
System settings need localization strings and need to be translated.

**Comment by NiceTSY** [comment]
Another thing that needs a localisation string is the reporting of Pool points needed for an ability.
I have not included it in my previous PR as I have not found a simple way yet.

I mean currently it is included like that:
`{{item.name}}{{#unless (or (eq data.costPoints "0") (eq data.costPoints 0) (eq data.costPoints ""))}} ({{data.costPoints}} {{data.costPool}} point{{#unless (eq data.costPoints "1")}}s{{/unless}}){{/unless}}`

This is great because we do not have a big "if" statement. But, less simple for the localisation ^^

**Comment by mrkwnzl** [comment]
> Another thing that needs a localisation string is the reporting of Pool points needed for an ability.
> I have not included it in my previous PR as I have not found a simple way yet.
> 
> I mean, currently, it is included like that:
> `{{item.name}}{{#unless (or (eq data.costPoints "0") (eq data.costPoints 0) (eq data.costPoints ""))}} ({{data.costPoints}} {{data.costPool}} point{{#unless (eq data.costPoints "1")}}s{{/unless}}){{/unless}}`
> 
> This is great because we do not have a big "if" statement. But, less simple for the localisation ^^

I created a separate issue for that (#78).
