### ISSUE TITLE
Eased roll does not show results

### ISSUE THREAD

**Issue by jorgeolothar** [mrkwnzl/cyphersystem-foundryvtt#83]
**Steps to reproduce the behavior**  
1- Drag the eased roll macro to the hot bar
2- Click on character
3- Roll eased roll, select "eased by" (6 in this example, roll of 5 in d20)

**Describe the bug**  
Result shows correct "eased by" text
However the "Beats difficulty" is unchanged
Also the roll itself is not affected (expected)

**Expected behavior**  
Result shows correct "eased by 6" text
"Beats difficulty" is changed to reflect number of steps eased (7)

**Screenshots**  
https://imgur.com/a/uZjsPEQ

**Setup**  
 - Cypher System Version: 1.13.8]
 - Foundry VTT Version: 0.7.9
 - Native App/Browser: Chrome

**Comment by mrkwnzl** [comment]
Hi! Thanks for reaching out. That is expected behavior. The idea is that you discuss and adjust the difficulty _before_ you roll. The steps eased/hindered are just a reminder for the GM in case there are multiple rolls, each of which has a different adjusted difficulty.

There is, however, a system setting that enables the behavior you want: [System Settings in the Wiki](https://github.com/mrkwnzl/cyphersystem-foundryvtt/wiki/System-Settings#roll-macros-use-effective-difficulty)
